# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be3d92fd216068a99f3c434aed6180597e4d693b7a154ae56d67a8ddedac591ac0d27fe947a4a49f29f55ac2fbbc0f757a03d8c0e570c57b5641573e53f1951

test:
  secret_key_base: c8e8e57f32329c65db484404a5bab252a9891863f7a98842ab624aec3cb2bef3a359c03194773f812e71e446f487a9ce316701e8eaf19f22b27a2ad2b656da1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
